server.port=8082
spring.application.name=mercado-express-mvc

# Thymeleaf Cache
spring.thymeleaf.cache=false

# Banco de Dados H2 em memoria para testes locais e desenvolvimento agil
spring.datasource.url=jdbc:h2:mem:mercadomvcdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracao Oracle FIAP (Descomente para conectar diretamente ao Oracle da FIAP)
# spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.username=RMxxxxx
# spring.datasource.password=suasenha
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# spring.jpa.hibernate.ddl-auto=update